### ISSUE TITLE
Roadmap for v3

### ISSUE THREAD

**Issue by maranomynet** [maranomynet/formatchange#1]
- Simplify all the things. Remove superfluous features:
  - [ ] Remove support for dynamic group reconfigurations
  - [ ] Move from class/OOP to simpler factory function
  - [ ] Remove `formatchange/jquery` and `formatchange/makeGroups`
  - [ ] Remove `withMediaProps`
  - [ ] Remove `Options.elmTagName`
  - [ ] Stop exposing `formatGroups` on the returned instance
- Better coding practices:
  - [ ] Make private variables actually private
  - [ ] Flag media object as `Readonly<>`  
  (Continue to keep track of `this.oldFormat` outside of `media`)
- Features: 
  - [ ] Allow optionally throttling the resize event
- Half-baked ideas: 
  - [ ] Remove ability to toggle on/off status
  - [ ] Handle montitored `elm` being removed from DOM
- Chores:
  - [ ] Rewrite README.md to reflect changes
